---
- name: Creating a daemon.json file
  copy:
    dest: "/etc/docker/daemon.json"
    content: '{ "dns": ["8.8.8.8","8.8.4.4"] }'

- name: Restart Docker
  service: name=docker state=restarted

- name: Create directory for docker-compose.yml files
  file:
    path: /srv/docker
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 755

- name: Adding ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Reset ssh connection
  meta: reset_connection

- name: Start single / master Docker Swarm node
  become: true
  become_user: ubuntu
  shell: docker swarm init || true